# Use root/example as user/password credentials
version: '3.1'

services:

  db-5:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080